services:
  amdv2:
    container_name: amdv2
    image: ghcr.io/chas0000/amdv2:latest
    network_mode: host
    environment:
      TTYD_USER: ""                  #TTYD的用户名和密码，两者都设定时才起效，否则为无鉴权模式
      TTYD_PASS: ""
    # 如果不使用 host 模式，可以使用端口映射
    # ports:
    #   - "7681:7681"
    volumes:
      - /mnt/disk1:/mnt/disk1        #映射需要保持音乐的目录，后半段需与config.toml中一致，自己修改
      - ./config/:/app2/config/      #amdv2的config.toml存放位置，第一次运行时会自动拷贝备份

